### ISSUE TITLE
Add correlation id for messages

### ISSUE THREAD

**Issue by DmitriySidorov** [solomoto-dev/GridDomain#38]
It will very good if we can restore message chain based on the correlation id. Correlation id generates for each application request and attached for each message which will create in business flow for creating a response.

**Comment by DmitriySidorov** [comment]
Correlation id should be generated in infrastructure layer. A user can pass some user-part of correlation id for filtering messages. For example, in some command I pass businessId as part of correlation => infrastructure generates correlation id as 'GUID_businessId'. In this approach, our correlation id will be unique for all application requests and we can filter messages by business id.

**Comment by andreyleskov** [comment]
Done in 2.0
